version: '3'

services:
  db:
    image: mysql
    volumes: 
      - db:/var/lib/mysql:delegated
    container_name: incident-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_USER_PASSWD}"
    ports:
      - "${DB_PORT}:3306"
    networks:
      net:
        ipv4_address: 172.80.0.2

  php:
    volumes: 
      - ./project:/var/www/html
    image: incident-php
    container_name: incident-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - "db"
    networks:
      net:
        ipv4_address: 172.80.0.3

  webserver:
    volumes: 
      - ./project:/var/www/html
    image: incident-ws
    container_name: incident-ws
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "${APP_HTTP_PORT}:80"
      - "${APP_HTTPS_PORT}:443"
    depends_on:
      - "php"
    networks:
      net:
        ipv4_address: 172.80.0.4

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 172.80.0.0/24
          gateway: 172.80.0.1

volumes:
  db:
